### ISSUE TITLE
Quaterniond coeff ordering inconsistency

### ISSUE THREAD

**Issue by ahundt** [jrl-umi3218/Eigen3ToPython#14]
It looks like [according to eigen](https://eigen.tuxfamily.org/dox/classEigen_1_1Quaternion.html) the Quaternion coeff ordering should be `wxyz`, in which case the identity should be `1,0,0,0` as follows:

```
 Quaternion (const Scalar &w, const Scalar &x, const Scalar &y, const Scalar &z)
```

I assume the coefficients would print in this same order but this seems like it might not be the case:
```
$ q = e.Quaterniond()
$ q.setIdentity()
$ print(np.array(q.coeffs()))
[[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]]
# w, x, y, z should also be identity for q2
$ q2 = e.Quaterniond(1,0,0,0)
$ qcoeffs = np.array(q.coeffs())
$ q2 = e.Quaterniond(qcoeffs[0,0],qcoeffs[1,0],qcoeffs[2,0],qcoeffs[3,0])
$ print(np.array(q2.coeffs()))
[[ 0.]
 [ 0.]
 [ 1.]
 [ 0.]]
# the angular distance between two identity quaternions should be zero
$ q.angularDistance(q2)
3.141592653589793
# The above doesn't seem right, it should be 0...
$ q2 = e.Quaterniond(1,0,0,0)
$ print(np.array(q2.coeffs()))
[[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]]
# shouldn't this be 1, 0, 0, 0?
$ q.angularDistance(q2)
0.0
# this is what I expected
$ q.w()
1.0
$ q.x()
0.0
$ q.y()
0.0
$ q.z()
0.0
$ vq2 = e.Vector4d(np.array([1,0,0,0]))
$ q2 = e.Quaterniond(vq2)
$ np.array(q2.coeffs())
array([[ 1.],
       [ 0.],
       [ 0.],
       [ 0.]])
$ q.angularDistance(q2)
3.141592653589793
```

**Comment by gergondet** [comment]
Hi Andrew,

It can be a bit confusing indeed :)

`coeffs()` returns a `Vector4d` so that the vector coefficients are `(x, y, z, w)` (see [doc](https://eigen.tuxfamily.org/dox/classEigen_1_1QuaternionBase.html#aa0e19f7cc477cf7d1e2a7b40a3a94cd4))

The constructor also handles a `Vector4d` and 4 scalars very differently.

This means that:

```python
v = eigen.Vector4d(0, 0, 0, 1) # (x, y, z, w)
q = eigen.Quaterniond(v) # q is Identity, q.coeffs() == v
q = eigen.Quaterniond(v(0), v(1), v(2), v(3)) # q is (0, 0, 1, 0)
```

which is why in your example: `q2 = e.Quaterniond(qcoeffs[0,0],qcoeffs[1,0],qcoeffs[2,0],qcoeffs[3,0])` is not what you expected.

**Comment by ahundt** [comment]
oh wow that's actually how it is done in eigen... I feel like the eigen authors had more consistent options available. :-/

I hadn't actually used coeffs directly in eigen before, how surprising. I'm going to add my session above to the docs so people can reference it.

**Comment by ahundt** [comment]
question is resolved, code is in the readme
