### ISSUE TITLE
Numpy to Vector3D

### ISSUE THREAD

**Issue by baptiste-mnh** [jrl-umi3218/Eigen3ToPython#22]
Hi!
Thank you for your work!
Is there a way to convert a numpy array (list of 3D points :  [ [x, y, z], [x, y, z ], ..., [x, y, z ] ]) into a eigen.Vector3d?
I tried different way but I couldn't make it works.

**Comment by haudren** [comment]
If you have a numpy array of size `(n, 3)` , there is no way to convert it into a *single* `Vector3d`. If you want to convert it to a list of `Vector3d` use this code:
```
import eigen
import numpy as np
A = np.array(range(300)).reshape((100,3))
vectors = [eigen.Vector3d(l) for l in A]
```

You can also convert it to a `MatrixXd`:
```
mat = eigen.MatrixXd(A)
```

However, we do not support matrices that have one fixed dim and one dynamic size (e.g. `Matrix<double, Dynamic, 3>`).

**Comment by baptiste-mnh** [comment]
Thanks for your response!
