### ISSUE TITLE
Incredible number of warnings

### ISSUE THREAD

**Issue by ahundt** [jrl-umi3218/Eigen3ToPython#7]
Building Eigen3ToPython creates an incredible number of repeating warnings which is breaking one of my travis-ci builds because they have a log size limit of 4.0 mb. 

Here is an example from [one of my builds](https://s3.amazonaws.com/archive.travis-ci.org/jobs/195745878/log.txt):
```
/home/travis/src/jrl-umi3218/Eigen3ToPython/build/src/eigen3.cpp:273:61: warning: cast from type â€˜const char*â€™ to type â€˜char*â€™ casts away qualifiers [-Wcast-qual]
     if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "", (char **) keywords)) {
```

Is there a clean way to actually fix the warning? If not, perhaps the flag can be set to disable it?

**Comment by gergondet** [comment]
All these warnings come from the code generated by PyBindGen and we cannot do anything to fix them. I've thus pushed [this commit](https://github.com/jrl-umi3218/Eigen3ToPython/commit/8654e1d75ec4a1c6326d45012ed08f4870254ed0) thath should silence all warnings from this package.

**Comment by ahundt** [comment]
@gergondet won't this block all warnings? would it be possible to just block the few relevant warnings?

```
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -w")
```

I know you have other bindings better than this anyway available but my build involves this version at the moment. :-)

**Comment by ahundt** [comment]
Also will that fail if the compiler is not gcc?

**Comment by haudren** [comment]
Well `clang++` also has a `-w` flag, not sure about VisualStudio, but I don't think it will break stuff... The real good thing to do would be to find what exactly is triggering the problem in `pybindgen` and fix it, but we are not really supporting it anymore...
